export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const SET_PROFILE_LOADING = "SET_PROFILE_LOADING";
export const CREATE_PROFILE = "CREATE_PROFILE";
